name: Build and Publish Electron App

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust the Node.js version to suit your project's needs

      - name: Install dependencies (including electron-forge)
        run: |
          npm install

      - name: Create keys directory and decode .pfx file
        env:
          PFX_BASE64: ${{ secrets.PFX_CERTIFICATE }}
        run: |
          mkdir -p keys
          echo "$PFX_BASE64" | base64 -d > keys/certificate.pfx

      - name: Publish Electron App
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx electron-forge publish
